###
POST http://localhost:8080/api/v2/auth/signup
Content-Type: application/json

{
    "name":"datsfvdsfa ",
    "email":"fsdfsg@gmail.com",
    "password":"1gvjbh",
    "phone":"24354ytuy54",
    "address":"gchuiohjb"
}